AWSTemplateFormatVersion: "2010-09-09"
Description: An encrypted bucket that will hold the datalake templates.
Resources:
  rS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub 'ians-datalake-template-for-${AWS::AccountId}'
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
Outputs:
  oS3Bucket:
    Value: !Ref rS3Bucket
