AWSTemplateFormatVersion: "2010-09-09"
Description: A job that moves data from the drop zone to the raw zone.
Parameters:
  pProjectName:
    Type: String
    Description: the project Name
Resources:
  rGlueJobDropToRaw:
    Type: AWS::Glue::Job
    Properties:
      #AllocatedCapacity: Double
      Command:
        Name: glueetl #default for apache spark jobs
        PythonVersion: 3
        ScriptLocation: s3://datalake-rww/glue-scripts/raw-to-curated-seller-performance.py
      DefaultArguments:
        "--database-name": !Sub '${pProjectName}-datalake-main-database'
        '--table-name': 'fill_this_in_later'
        "--job-bookmark-option": "job-bookmark-enable"
      Description: Join a few tables to create a new one, ready to be imported into Redshift.
      Name: !Sub '${pProjectName}-glue-job-raw-to-curated-seller-performance'
      Role: arn:aws:iam::773548596459:role/AWSGlueAdmin
