AWSTemplateFormatVersion: "2010-09-09"
Description: A job that moves data from the drop zone to the raw zone.
Parameters:
  pProjectName:
    Type: String
    Description: the ARN of the dead letter queue
  rGlueJobDropToRaw:
    Type: AWS::Glue::Job
    Properties:
      #AllocatedCapacity: Double
      Command:
        Name: glueetl #default for apache spark jobs
        PythonVersion: 3
        ScriptLocation: s3://datalake-rww/glue-scripts/test.py
      DefaultArguments:
        -
          '--database-name': !Sub '${pProjectName}-datalake-main-database'
          '--table-name': 'person'
      Description: Convert incoming CSV to Parquet.
      Name: !Sub '${pProjectName}-glue-job-drop-to-raw'
      Role: arn:aws:iam::773548596459:role/AWSGlueAdmin
