AWSTemplateFormatVersion: '2010-09-09'
Description: builds a HIPAA-compliant datalake
Parameters:
  pProjectName:
    Type: String
    Description: overall project name which will be used for tags
Resources:
  #IAM to produce the roles.
  rDeadLetterQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        pProjectName: !Ref pProjectName
        pQueueName: !Sub '${pProjectName}-dead-letter-queue'
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/queue-dead-letter.yaml
      TimeoutInMinutes: 5
  rDropZone:
    Type: AWS::CloudFormation::Stack
    DependsOn: rDeadLetterQueue
    Properties:
      Parameters:
        pDeadLetterQueueArn: !GetAtt rDeadLetterQueue.Outputs.rQueueArn
        pDownstreamZone: raw
        pKeyAdministrator: arn:aws:iam::773548596459:user/robwhelan
        pKeyUser: arn:aws:iam::773548596459:role/lambda_basic_execution
        pProjectName: !Ref pProjectName
        pSqsQueueVisibilityTimeout: 120
        pTransitionClass: GLACIER
        pTransitionInDays: 7
        pZone: drop
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/zone.yaml
      TimeoutInMinutes: 15

  #vpc
  #config rules
  #logging
  #other security, like macie
