AWSTemplateFormatVersion: '2010-09-09'
Description: builds a HIPAA-compliant datalake
Parameters:
  pProjectName:
    Type: String
    Description: overall project name which will be used for tags
Resources:
  #IAM to produce the roles.
  rIam:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        pProjectName: !Ref pProjectName
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/iam.yaml
      TimeoutInMinutes: 5

  #dead letter queue for general failures
  rDeadLetterQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        pProjectName: !Ref pProjectName
        pQueueName: !Sub '${pProjectName}-dead-letter-queue'
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/queue-dead-letter.yaml
      TimeoutInMinutes: 5
  rDropZone:
    Type: AWS::CloudFormation::Stack
    DependsOn: rDeadLetterQueue
    Properties:
      Parameters:
        pDeadLetterQueueArn: !GetAtt rDeadLetterQueue.Outputs.rQueueArn
        pDownstreamZone: raw
        pKeyAdministrator: arn:aws:iam::773548596459:user/robwhelan
        pKeyUser: arn:aws:iam::773548596459:role/lambda_basic_execution
        pProjectName: !Ref pProjectName
        pSqsQueueVisibilityTimeout: 120
        pTransitionClass: GLACIER
        pTransitionInDays: 7
        pZone: drop
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/zone.yaml
      TimeoutInMinutes: 15

  #vpc
  rVpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        pProjectName: !Ref pProjectName
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/network.yaml
      TimeoutInMinutes: 5

  #main database for data catalog.
  rGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
          Description: Central virtual database for all tables in the data lake.
          #LocationUri: String
          Name: !Sub '${pProjectName}-datalake-main-database'

  #config rules
  #logging
  #other security, like macie
