AWSTemplateFormatVersion: '2010-09-09'
Description: builds a HIPAA-compliant datalake
Parameters:
  pProjectName:
    Type: String
    Description: overall project name which will be used for tags
Resources:
  #add a dead letter queue arn.
  rDeadLetterQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        pProjectName: !Ref pProjectName
        pQueueName: !Sub '${pProjectName}-dead-letter-queue'
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/queue-dead-letter.yaml
      TimeoutInMinutes: 5
  #drop zone bucket -- TODO: add that this DependsOn the dead letter queue.
  rDropZone:
    Type: AWS::CloudFormation::Stack
    DependsOn: rDeadLetterQueue
    Properties:
      Parameters:
        pDeadLetterQueueArn: !GetAtt rDeadLetterQueue.Outputs.rQueueArn
        pKeyAdministrator: arn:aws:iam::773548596459:user/robwhelan
        pKeyUser: arn:aws:iam::773548596459:role/service-role/accountable-SMS-Role
        pProjectName: !Ref pProjectName
        pSqsQueueVisibilityTimeout: 120
        pTransitionClass: GLACIER
        pTransitionInDays: 7
        pZone: drop
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/zone.yaml
      TimeoutInMinutes: 15
  #raw zone
  #vpc
  #config rules
  #iam
  #logging
  #kms keys...
  #other security, like macie
Outputs:
  rDropZone:
    Value: !Ref rDropZone
