AWSTemplateFormatVersion: '2010-09-09'
Description: builds a basic datalake with 3 zones and dedicated encryption keys.
Parameters:
  pProjectName:
    Type: String
    Description: overall project name which will be used for tags and resource naming.
Resources:
  #IAM to produce the roles.
  rIam:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        pProjectName: !Ref pProjectName
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/iam.yaml
      TimeoutInMinutes: 5

  rDropZone:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - rDeadLetterQueue
    Properties:
      Parameters:
        pDeadLetterQueueArn: !GetAtt rDeadLetterQueue.Outputs.rQueueArn
        pKeyAdministrator: arn:aws:iam::773548596459:user/robwhelan
        pKeyUser: arn:aws:iam::773548596459:role/lambda_basic_execution
        pProjectName: !Ref pProjectName
        pSqsQueueVisibilityTimeout: 120
        pTransitionClass: GLACIER
        pTransitionInDays: 7
        pZone: drop
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/zone.yaml
      TimeoutInMinutes: 15

  rRawZone:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - rDeadLetterQueue
    Properties:
      Parameters:
        pDeadLetterQueueArn: !GetAtt rDeadLetterQueue.Outputs.rQueueArn
        pKeyAdministrator: arn:aws:iam::773548596459:user/robwhelan
        pKeyUser: arn:aws:iam::773548596459:role/lambda_basic_execution
        pProjectName: !Ref pProjectName
        pSqsQueueVisibilityTimeout: 120
        pTransitionClass: GLACIER
        pTransitionInDays: 7
        pZone: raw
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/zone.yaml
      TimeoutInMinutes: 15

  rCuratedZone:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - rDeadLetterQueue
    Properties:
      Parameters:
        pDeadLetterQueueArn: !GetAtt rDeadLetterQueue.Outputs.rQueueArn
        pKeyAdministrator: arn:aws:iam::773548596459:user/robwhelan
        pKeyUser: arn:aws:iam::773548596459:role/lambda_basic_execution
        pProjectName: !Ref pProjectName
        pSqsQueueVisibilityTimeout: 120
        pTransitionClass: GLACIER
        pTransitionInDays: 7
        pZone: curated
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/zone.yaml
      TimeoutInMinutes: 15

  #main database for data catalog.
  rEtlPipeline:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - rDropZone
      - rRawZone
      - rCuratedZone
    Properties:
      Parameters:
        pProjectName: !Ref pProjectName
        pDropZone: !GetAtt rDropZone.Outputs.oS3Bucket
        pRawZone: !GetAtt rRawZone.Outputs.oS3Bucket
        pCuratedZone: !GetAtt rCuratedZone.Outputs.oS3Bucket
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/etl.yaml
      TimeoutInMinutes: 5

  #cloudtrail logging
  #rCloudtrailTrail:
  #  Type: AWS::CloudFormation::Stack
  #  DependsOn: rLoggingBucket
  #  Properties:
  #    Parameters:
  #      pLoggingBucket: !Ref rLoggingBucket
  #    TemplateURL: https://datalake-rww.s3.amazonaws.com/monitoring/cloudtrail.yaml
  #    TimeoutInMinutes: 5

  #Monitoring
  #dead letter queue for general failures
  rDeadLetterQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        pProjectName: !Ref pProjectName
        pQueueName: !Sub '${pProjectName}-dead-letter-queue'
      TemplateURL: https://datalake-rww.s3.amazonaws.com/components/queue-dead-letter.yaml
      TimeoutInMinutes: 5

  #central logging bucket for any logging event - s3 access logging, cloudtrail.
  #TODO: this must be in a different account later.
  #config rules
  #logging
  #other security, like macie

Outputs:
  oDropZoneBucket:
    Value: !GetAtt rDropZone.Outputs.oS3Bucket
