AWSTemplateFormatVersion: "2010-09-09"
Description: ETL infrastructure
Resources:
  rGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
          Description: my database
          #LocationUri: String
          Name: smalldatabasefortest
  rGlueCrawler:
    Type: AWS::Glue::Crawler
    DependsOn: rGlueDatabase
    Properties:
      DatabaseName: !Ref rGlueDatabase
      Description: Crawls sales data to establish table
      Name: sales-crawler
      Role: arn:aws:iam::773548596459:role/AWSGlueAdmin
      SchemaChangePolicy:
        DeleteBehavior: DEPRECATE_IN_DATABASE
        UpdateBehavior: UPDATE_IN_DATABASE
      TablePrefix: 'sales-'
      Targets:
        S3Targets:
          - Path: 's3://bigdatalabsrww/glue-test/'
          - Path: 's3://bigdatalabsrww/glue-test-next/'
