AWSTemplateFormatVersion: "2010-09-09"
Description: ETL infrastructure. Glue database, crawler for each zone, and jobs.
Parameters:
  pProjectName:
    Type: String
  pDropZoneBucket:
    Type: String
  pRawZoneBucket:
    Type: String
  pCuratedZoneBucket:
    Type: String
Resources:
  #glue service role. Reference the glue managed policy.
  #then, create a custom policy that allows glue to read and write to the s3 buckets.

  rGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
          Description: Central virtual database for all tables in the data lake.
          #LocationUri: String
          Name: !Sub '${pProjectName}-datalake-main-database'
  rGlueCrawlerDropZone:
    Type: AWS::Glue::Crawler
    Properties:
      DatabaseName: !Ref rGlueDatabase
      Description: Crawls data in the drop zone to establish table
      Name: !Sub '${pProjectName}-datalake-crawler-dropzone'
      Role: arn:aws:iam::773548596459:role/AWSGlueAdmin
      SchemaChangePolicy:
        DeleteBehavior: DEPRECATE_IN_DATABASE
        UpdateBehavior: UPDATE_IN_DATABASE
      TablePrefix: !Sub '${pProjectName}_drop_' #generalize this
      Targets:
        S3Targets:
          - Path: !Sub 's3://${pDropZoneBucket}/'
  rGlueCrawlerRawZone:
    Type: AWS::Glue::Crawler
    Properties:
      DatabaseName: !Ref rGlueDatabase
      Description: Crawls data to establish table in the raw zone - general analytics.
      Name: !Sub '${pProjectName}-datalake-crawler-rawzone'
      Role: arn:aws:iam::773548596459:role/AWSGlueAdmin
      SchemaChangePolicy:
        DeleteBehavior: DEPRECATE_IN_DATABASE
        UpdateBehavior: UPDATE_IN_DATABASE
      TablePrefix: !Sub '${pProjectName}_raw_' #generalize this
      Targets:
        S3Targets:
          - Path: !Sub 's3://${pRawZoneBucket}/closed-deals/'
          - Path: !Sub 's3://${pRawZoneBucket}/order-items/'
          - Path: !Sub 's3://${pRawZoneBucket}/order-reviews/'
          - Path: !Sub 's3://${pRawZoneBucket}/sellers/'
          #TODO: get rid of hard-coding of s3 targets.
  rGlueCrawlerCuratedZone:
    Type: AWS::Glue::Crawler
    Properties:
      DatabaseName: !Ref rGlueDatabase
      Description: Crawls data to establish table in the curated zone for a data mart.
      Name: !Sub '${pProjectName}-datalake-crawler-curatedzone'
      Role: arn:aws:iam::773548596459:role/AWSGlueAdmin
      SchemaChangePolicy:
        DeleteBehavior: DEPRECATE_IN_DATABASE
        UpdateBehavior: UPDATE_IN_DATABASE
      TablePrefix: !Sub '${pProjectName}_curated_' #generalize this
      Targets:
        S3Targets:
          - Path: !Sub 's3://${pCuratedZoneBucket}/'
#TODO: add tags and other metadata to the tables. Can you do this here, or after the table is creqated?
