AWSTemplateFormatVersion: "2010-09-09"
Description: ETL infrastructure
Parameters:
  pGlueDatabase:
    Type: String
    Description: overall project name which will be used for tags
Resources:
  rGlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      DatabaseName: !Ref pGlueDatabase
      Description: Crawls data to establish table
      Name: medicare-payments-crawler
      Role: arn:aws:iam::773548596459:role/AWSGlueAdmin
      SchemaChangePolicy:
        DeleteBehavior: DEPRECATE_IN_DATABASE
        UpdateBehavior: UPDATE_IN_DATABASE
      TablePrefix: 'medicare-' #generalize this
      Targets:
        S3Targets:
          - Path: 's3://bigdatalabsrww/medicare/'
          - Path: 's3://bigdatalabsrww/glue-test-next/'
