AWSTemplateFormatVersion: "2010-09-09"
Description: VPC infrastructure
Parameters:
  pProjectName:
    Type: String
    Description: overall project name which will be used for tags
Resources:
  rProprietaryAccessPolicy:
    DependsOn: rProprietaryAccessGroup
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref rProprietaryAccessGroup
      PolicyDocument: #denies access to any data in s3 that is higher security than confidential or secret.
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Deny"
              Action:
                - "s3:GetObject"
              Resource: "*"
              Condition:
                ForAnyValue:StringEqualsIgnoreCase:
                  s3:ExistingObjectTag/dataclassification:
                    - confidential
                    - secret
      PolicyName: !Sub '${pProjectName}-proprietary-access-policy'
  rConfidentialAccessPolicy:
    DependsOn: rConfidentialAccessGroup
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref rConfidentialAccessGroup
      PolicyDocument: #denies access to any data in s3 that is higher security than confidential or secret.
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Deny"
              Action:
                - "s3:GetObject"
              Resource: "*"
              Condition:
                StringEqualsIgnoreCase:
                  s3:ExistingObjectTag/dataclassification: secret
      PolicyName: !Sub '${pProjectName}-confidential-access-policy'

  rDataEngineerExtraPolicies:
    DependsOn: rDataEngineerGroup
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref rDataEngineerGroup
      PolicyDocument: #glue, step functions, emr, athena
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Action:
                - "athena:*"
                - "emr:*"
                - "glue:*"
                - "states:*" #step functions
              Resource: "*"
      PolicyName: !Sub '${pProjectName}-extra-data-engineer-policies'
  rDataAnalystExtraPolicies:
    DependsOn: rDataAnalystGroup
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref rDataAnalystGroup
      PolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Action:
                - "athena:*"
              Resource: "*"
      PolicyName: !Sub '${pProjectName}-extra-data-analyst-policies'

  rDataStewardGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-data-steward'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /job/data-steward/
  rDataEngineerGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-data-engineer'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/DatabaseAdministrator
      Path: /job/data-engineer/
  rDataScientistGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-data-scientist'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/DataScientist
      Path: /job/data-scientist/
  rDataAnalystGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-data-analyst'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/DatabaseAdministrator
      Path: /job/data-analyst/

  rProprietaryAccessGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-proprietary-data-access'
      Path: /access-level/proprietary/
  rConfidentialAccessGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-confidential-data-access'
      Path: /access-level/confidential/
  rSecretAccessGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-secret-data-access'
      Path: /access-level/secret/
