AWSTemplateFormatVersion: "2010-09-09"
Description: VPC infrastructure
Parameters:
  pProjectName:
    Type: String
    Description: overall project name which will be used for tags
Resources:
  rDataEngineerExtraPolicies:
    DependsOn: rDataEngineerGroup
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref rDataEngineerGroup
      PolicyDocument: #glue, step functions, emr, athena
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Action:
                - "athena:*"
                - "emr:*"
                - "glue:*"
                - "states:*" #step functions
              Resource: "*"
      PolicyName: !Sub '${pProjectName}-extra-data-engineer-policies'
  rDataAnalystExtraPolicies:
    DependsOn: rDataAnalystGroup
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref rDataAnalystGroup
      PolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Action:
                - "athena:*"
              Resource: "*"
      PolicyName: !Sub '${pProjectName}-extra-data-analyst-policies'
  rDataStewardGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-data-steward'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /job/data-steward/
  rDataEngineerGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-data-engineer'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/DatabaseAdministrator
      Path: /job/data-engineer/
  rDataScientistGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-data-scientist'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/DataScientist
      Path: /job/data-scientist/
  rDataAnalystGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-data-analyst'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/DatabaseAdministrator
      Path: /job/data-analyst/
  rProprietaryDataGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-proprietary-data-access'
      Path: /access-level/proprietary/
  rConfidentialDataGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-confidential-data-access'
      Path: /access-level/confidential/
  rSecretDataGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${pProjectName}-secret-data-access'
      Path: /access-level/secret/
